include: [legal]
# General Jekyll Config
highlighter: rouge
url: https://autodo.app
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
sass:
    sass_dir: _includes/_sass