#page title
title: auToDo

# App Info
ios_app_id                                : 1498684737                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.autodo.autodo
# presskit_download_link                    : https://emilbaehr.com                     # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : auToDo                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
# header_name: auToDo
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Car Maintenance Tracking Made Simple.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
# your_name                                 : Jonathan Bayless and David Pham-Van                              
# your_link                                 : https://emilbaehr.com                     
# your_city                                 :                               
email_address                             : contact@autodo.app
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : autodoApp
github_username                           : autodo-app
youtube_username                          :

developers:
  - name: Jonathan Bayless
    url: https://jonathanbayless.com
  - name: David Pham-Van
    url: https://github.com/davbfr

features:
  - title: Maintenance Reminders
    description: Get reminders for your car's routine maintenance that are persistent without being annoying.
    fontawesome_icon_name: bell
  - title: Set Once and Forget It
    description: Create a repeating task and auToDo will help make sure you never forget it again.
    fontawesome_icon_name: sync
  - title: Own Your Car's Data
    description: Every time you log a refueling of your car <b>your</b> repeating tasks get more accurate notifications.
    fontawesome_icon_name: lock
  - title: Statistics
    description: Statistics on your car and its maintenance gives you the information you need to know how your car is performing, and the ability to easily create recurring tasks means <b>you don't have to worry about forgetting a task again.</b>
    fontawesome_icon_name: chart-line
  - title: Defaults
    description: auToDo adds a set of common routine maintenance tasks by default, all of which recur on a mileage interval that you control. You can add add and remove tasks from this set of defaults to <b>match the exact needs of your vehicle.</b>
    fontawesome_icon_name: edit
  - title: Easily Create Tasks
    description: <b>Creating a standalone ToDo item is a breeze</b>. Just enter the name and due date (or mileage) of the action and associate it with any or all of your vehicles.
    fontawesome_icon_name: magic

# Theme Settings
topbar_color                              : "#4cc8a7"
topbar_transparency                       : 0.9
topbar_title_color                        : "#eee"

cover_image                               : assets/headerNoLogo.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#eee"

link_color                                : "darken(#4cc8a7, 15%)"

app_title_color                           : "#eee"
app_price_color                           : "#ccc"
app_description_color                     : "#eee"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "darken(#4cc8a7, 5%)"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

include: [legal]
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

plugins:
    - jekyll-feed
    - jekyll-redirect-from
whitelist:
    - jekyll-redirect-from
highlighter: rouge
url: https://autodo.app
lsi: false
google_analytics_key: UA-145122049-1